baseURL = "https://dadascience.design/portfolio"
# baseURL = "https://dadascience.design/"
languageCode = "en-us"
title = "fubits@git"

publishDir = "../ellocke.github.io/portfolio"

theme = "meghna-hugo"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disableKinds = ["taxonomy", "taxonomyTerm"]

# Menu
[menu]
    [[menu.nav]]
    name = "Home"
    URL = "../"
    weight = 1

    [[menu.nav]]
    name = "Posts"
    URL = "../post"
    weight = 2

    [[menu.nav]]
    name = "Portfolio"
    URL = "../portfolio"
    weight = 3
    
    [[menu.nav]]
    name = "Talks"
    URL = "../talks"
    weight = 4
    
    [[menu.nav]]
    name = "About"
    URL = "../about"
    weight = 5

# Site params
[params]
home= "fubits@git Portfolio"
logo = "images/logo.png"

# Meta data
description = "Portfolio - fubits@git"
author = "Ilja / fubits"

custom_css = ["css/custom.css"]

# Banner Section
[params.banner]
enable = true
bgImage = "images/backgrounds/john-barkiple-539580-unsplash.jpg"
icon = "tf-ion-play"
heading = "Freelance Portfolio"
content= "Computational Social Science | HCI/UX | Data & Information Visualisation | GIS/Mapping | Open Science | Research Data Management"
btn = true
btnText="Explore"
btnURL="mission"

# call to action
[params.cta]
enable = true
title = "Custom Solutions for Non-Profit Research"
content = ""
btnURL = "https://keybase.io/fubits/"
btnText = "Contact Me"

# counter
[params.counter]
enable = false
bgImage = "images/backgrounds/bg-1.jpg"

# footer
[params.footer]
    copyright = "© Ilja / fubits"
    copyrightURL = "http://www.dadascience.design/about"
    theme = "© Meghna Hugo by Themefisher"
    themeURL = "https://themes.gohugo.io/meghna-hugo/"
    themeLicense = "CC BY 3.0"
    themeLicenseURL = "https://creativecommons.org/licenses/by/3.0/"
    pageLicense = "CC BY-SA 4.0"
    pageLicenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"

# social Icons

[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "https://twitter.com/fubits"

[[params.footer.socialIcon]]
icon = "tf-ion-key"
url = "https://keybase.io/fubits/"

[[params.footer.socialIcon]]
icon = "tf-ion-social-github"
url = "https://github.com/ellocke/"

[[params.footer.socialIcon]]
icon = "tf-ion-social-linkedin"
url = "https://www.linkedin.com/in/ilja-sperling/"
