baseURL = "https://dadascience.design/portfolio"
languageCode = "en-us"
title = "fubits@Portfolio"

publishDir = "../ellocke.github.io/portfolio"

theme = "meghna-hugo-upstream"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disableKinds = ["taxonomy", "taxonomyTerm"]

# Menu
[menu]
    [[menu.nav]]
    name = "Home"
    URL = "../"
    weight = 1

    [[menu.nav]]
    name = "Posts"
    URL = "../post"
    weight = 2

    [[menu.nav]]
    name = "Portfolio"
    URL = "../portfolio"
    weight = 3
    
    [[menu.nav]]
    name = "About"
    URL = "../about"
    weight = 4

# Site params
[params]
home= "fubits@Portfolio"
logo = "images/logo.png"

# Meta data
description = "Freelance Product Design & Data Science Portfolio Ilja Sperling | fubits"
author = "Ilja | @fubits"

custom_css = ["css/custom.css"]

# Banner Section
[params.banner]
enable = true
bgImage = "images/backgrounds/fubits_isometric.jpg"
icon = "tf-ion-play"
heading = "Freelance Portfolio"
content = ["Product Design & UX", "Computational Social Science" , "GIS/Mapping" , "Data & Information Visualisation" , "Research Data Management","Open Science"]
btn = true
btnText = "EXPLORE"
btnURL = "mission"

# call to action
[params.cta]
enable = true
title = "Efficient Product Design for Not-for-Profit Action"
content = ""
btnURL = "https://keybase.io/fubits/"
btnText = "Reach out"

# counter
[params.counter]
enable = false
bgImage = "images/backgrounds/dot-map.jpg"

# footer
[params.footer]
    copyright = "© Ilja / fubits"
    copyrightURL = "http://www.dadascience.design/about"
    theme = "© Meghna Hugo by Themefisher"
    themeURL = "https://themes.gohugo.io/meghna-hugo/"
    themeLicense = "CC BY 3.0"
    themeLicenseURL = "https://creativecommons.org/licenses/by/3.0/"
    pageLicense = "CC BY-SA 4.0"
    pageLicenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"

# social Icons

[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "https://twitter.com/fubits"

[[params.footer.socialIcon]]
icon = "tf-ion-social-key"
url = "https://keybase.io/fubits/"

[[params.footer.socialIcon]]
icon = "tf-ion-social-github"
url = "https://github.com/ellocke/"

[[params.footer.socialIcon]]
icon = "tf-ion-social-linkedin"
url = "https://www.linkedin.com/in/ilja-sperling/"
